//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14pt")]
        public global::System.Drawing.Font ButtonFont {
            get {
                return ((global::System.Drawing.Font)(this["ButtonFont"]));
            }
            set {
                this["ButtonFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color ButtonTextColour {
            get {
                return ((global::System.Drawing.Color)(this["ButtonTextColour"]));
            }
            set {
                this["ButtonTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ButtonFace")]
        public global::System.Drawing.Color ButtonBackColour {
            get {
                return ((global::System.Drawing.Color)(this["ButtonBackColour"]));
            }
            set {
                this["ButtonBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color OperatorTextColour {
            get {
                return ((global::System.Drawing.Color)(this["OperatorTextColour"]));
            }
            set {
                this["OperatorTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppWorkspace")]
        public global::System.Drawing.Color OperatorBackColour {
            get {
                return ((global::System.Drawing.Color)(this["OperatorBackColour"]));
            }
            set {
                this["OperatorBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14pt")]
        public global::System.Drawing.Font AnswerFont {
            get {
                return ((global::System.Drawing.Font)(this["AnswerFont"]));
            }
            set {
                this["AnswerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WindowText")]
        public global::System.Drawing.Color AnswerTextColour {
            get {
                return ((global::System.Drawing.Color)(this["AnswerTextColour"]));
            }
            set {
                this["AnswerTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Window")]
        public global::System.Drawing.Color AnswerBackColour {
            get {
                return ((global::System.Drawing.Color)(this["AnswerBackColour"]));
            }
            set {
                this["AnswerBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ActiveCaption")]
        public global::System.Drawing.Color BagroundColour {
            get {
                return ((global::System.Drawing.Color)(this["BagroundColour"]));
            }
            set {
                this["BagroundColour"] = value;
            }
        }
    }
}
